defaultPage:
    path: /
    controller: AppBundle\Controller\StartpageController::indexAction

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{dbversion}/
    requirements:
      dbversion: '%versions%'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

github_check:
    path: /login/check-github

github_login:
    path: /connect/github

logout:
    path: /logout

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type: annotation
    prefix: /admin